name: Testing, Building, and Publishing

on:
  push:
    branches:
      - main
      - release-binary
      # - '*'         # matches every branch that doesn't contain a '/'
      # - '*/*'       # matches every branch containing a single '/'
      # - '**'        # matches every branch
      # - '!main'     # excludes master

# on:
#   push:
#     tags:
#     - '*'

jobs:
  # test:
  #   name: Testing
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest] #, macos-latest, windows-latest]  # ! FIXME: Add windows
  #       python-version: [3.9]  # ! FIXME: Add 3.7

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Display Python version
  #       run: python -c "import sys; print(sys.version)"

  #     - name: Update APT
  #       if: matrix.os == 'ubuntu-latest'
  #       run: sudo apt-get update

  #     - name: Install Linux simpleaudio dependency
  #       if: matrix.os == 'ubuntu-latest'
  #       run: sudo apt-get install -y python3-dev libasound2-dev

  #     - name: Install pipenv
  #       run: |
  #         python -m pip install --upgrade-strategy=only-if-needed pip pipenv

  #     - id: cache-pipenv
  #       uses: actions/cache@v2.1.7
  #       with:
  #         path: ~/.local/share/virtualenvs
  #         key: ${{ runner.os }}-pipenv-V2-${{ hashFiles('**/Pipfile.lock') }}

  #     - name: Install dependencies if not in cache
  #       if: steps.cache-pipenv.outputs.cache-hit != 'true'
  #       run: pipenv sync --dev

  #     - name: Show All dependencies
  #       run: pipenv graph

  #     - name: Code Linting
  #       run: pipenv run pylint ./yojenkins --rcfile=.pylintrc --fail-under=9.0

  #     - name: Build the package
  #       run: pipenv run python setup.py install --verbose

  #     - name: Testing --help
  #       run: pipenv run yojenkins --help


  # --------------------------------------------------------------------------


  build-binaries:
    name: Building Binaries
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update APT
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: Install Linux simpleaudio dependency
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y python3-dev libasound2-dev

      - name: Install pipenv
        run: python -m pip install --upgrade-strategy=only-if-needed pip pipenv

      - id: cache-pipenv
        uses: actions/cache@v2.1.7
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-V2-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies if not in cache
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv sync --dev

      - name: Build with PyInstaller
        env:
          PYTHONOPTIMIZE: 1 # Enable optimizations as if the -O flag is given.
          PYTHONHASHSEED: 42 # Try to ensure deterministic results.
        run: pipenv run pyinstaller pyinstaller-onefile.spec -y --clean

      - name: List distribution files
        run: find dist

      - name: Rename binary artifact (Linux)
        if: (matrix.os == 'ubuntu-latest')
        run: mv dist/yojenkins* dist/yojenkins-linux-x86_64

      - name: Rename binary artifact (MacOS)
        if: (matrix.os == 'macos-latest')
        run: mv dist/yojenkins* dist/yojenkins-macos-x86_64

      - name: Rename binary artifact (Windows)
        if: (matrix.os == 'windows-latest')
        run: mv dist/yojenkins*.exe dist/yojenkins-windows-x86_64.exe

      - uses: actions/upload-artifact@v2
        with:
          name: binary-${{ runner.os }}
          path: dist/


  # --------------------------------------------------------------------------


  build-package:
    name: Building Package
    needs: [test]
    runs-on: ubuntu-latest

    # TODO: Add check to see if bumpversion has been run, if not, skip

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Linux simpleaudio dependency
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y python3-dev libasound2-dev

      - name: Install pipenv
        run: python -m pip install --upgrade-strategy=only-if-needed pip pipenv

      - id: cache-pipenv
        uses: actions/cache@v2.1.7
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-V2-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies if not in cache
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv sync --dev

      - name: Install pypa/build tooling
        run: pipenv run python -m pip install build

      - name: Build a package wheel and tarball
        run: pipenv run python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: pypi-distribution
          path: dist/

  # --------------------------------------------------------------------------


  release-binary:
    name: Releasing Binaries to GitHub Releases
    needs: [build-binaries]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    # TODO: Add check to see if bumpversion has been run, if not, skip

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binary-${{ runner.os }}
          path: dist/

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          artifacts: "dist/*"
          body: "testing"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true


  # --------------------------------------------------------------------------


  release-package:
    name: Releasing Package to PyPI
    needs: [build-package]
    runs-on: ubuntu-latest

    # TODO: Add check to see if bumpversion has been run, if not, skip

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: pypi-distribution
          path: dist/

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          artifacts: "dist/*"
          body: "testing"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

      - name: Publish distribution 📦 to TEST PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
