name: Testing Install and Run

on:
  push:
    branches:
      - '!main'     # excludes main
    tags:
      - "*"

jobs:
  test:
    name: Install and Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]  # ! FIXME: Add windows
        python-version: [3.10] # ! FIXME: Add 3.7

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Update apt package repositories
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update

      - name: Install Linux simpleaudio dependency
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y python3-dev libasound2-dev

      - name: Install pipenv
        run: |
          python -m pip install --upgrade-strategy=only-if-needed pip pipenv

      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-V3-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies if not in cache
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv sync --dev

      - name: Show All dependencies
        run: pipenv graph

      - name: Code Linting
        run: pipenv run pylint ./yojenkins --rcfile=.pylintrc

      - name: Build the package
        run: pipenv run python setup.py install --verbose

      - name: Testing --help
        run: pipenv run yojenkins --help
